spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.chjxpiygt7p4.ap-northeast-2.rds.amazonaws.com/najakgil?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: najakgil
    password: devgil0819
  sql:
    init:
      platform: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      access-key: AKIAWNFTLQPXNPS4JKL2
      secret-key: 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
    s3: #버킷이름
      bucket: najakgil
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: "Tz2mze7c52RlnOnnhObQaKJijW9bD1lY3xBISlh1J7y6BmXN27qf6RfHSmFeJcL9weOOseaJGDyL9CTMaSAcDg=="




