spring:
  config:
    activate:
      on-profile: local
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:najakgil;NON_KEYWORDS=USER
    username: root
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: "Tz2mze7c52RlnOnnhObQaKJijW9bD1lY3xBISlh1J7y6BmXN27qf6RfHSmFeJcL9weOOseaJGDyL9CTMaSAcDg=="
  access:
    #expiration: 300000 #5분 (5 * 60) * 1000
    expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
    header: "X-AUTH-TOKEN"
  refresh:
    expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
    header: "X-REFRESH-TOKEN"


cloud:
  aws:
    credentials:
      access-key: AKIAWNFTLQPXNPS4JKL2
      secret-key: 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
    s3: #버킷이름
      bucket: najakgil
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false